#!/bin/bash

MOD=$1
IN=$2
OUT=$3

usage () {
    echo -e "Usage:"
    echo -e "\t$0 e|d input output"
}

if [ "X$IN" == "X" ]; then
    usage
    exit 1
elif [ "X$OUT" == "X" ]; then
    usage
    exit 1
fi

if [ "$MOD" == "e" ]; then
    openssl aes-128-cbc -salt -md md5 -in $IN -out $OUT
elif [ "$MOD" == "d" ]; then
    openssl aes-128-cbc -d -salt -md md5 -in $IN -out $OUT
else
    usage
    exit 1
fi
